image:
  name: golang:1.13.1-stretch
  entrypoint: ["/bin/sh", "-c"]

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is mydomainperso.com, and that your repository is repos/projectname, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/mydomainperso.com/repos/projectname
# Thus, making a symbolic link corrects this.
# 为了能够使用go get，需要将代码放在 $GOPATH 中，
# 比如你的 gitlab 域名是 mydomain.com，你的代码仓库是 repos/projectname，
# 默认的 GOPATH 是 /go，然后你就需要将你的代码放置到 GOPATH 下面，
# /go/src/mydomain.com/repos/projectname，用一个软链接指过来就可以了
before_script:
  - mkdir -p "/go/src/git.qikqiak.com/${CI_PROJECT_NAMESPACE}"
  - ln -sf "${CI_PROJECT_DIR}" "/go/src/git.qikqiak.com/${CI_PROJECT_PATH}"
  - cd "/go/src/git.qikqiak.com/${CI_PROJECT_PATH}/"

stages:
  - test
  - build
  - release
  - review
  - deploy

test:
  stage: test
  script:
    - make test

test2:
  stage: test
  script:
    - sleep 3
    - echo "We did it! Something else runs in parallel!"
    - echo $CI
    - echo $CI_BUILDS_DIR
    - echo $CI_COMMIT_BEFORE_SHA
    - echo $CI_COMMIT_DESCRIPTION
    - echo $CI_COMMIT_SHA
    - echo $CI_COMMIT_TAG
    - echo $CI_CONFIG_PATH
    - echo $CI_DEFAULT_BRANCH
    - echo $CI_DEPLOY_PASSWORD
    - echo $CI_ENVIRONMENT_NAME
    - echo $CI_JOB_ID
    - echo $CI_JOB_IMAGE
    - echo $CI_JOB_MANUAL
    - echo $CI_JOB_NAME
    - echo $CI_PIPELINE_ID
    - echo $CI_PIPELINE_SOURCE
    - echo $CI_PIPELINE_TRIGGERED
    - echo $CI_PROJECT_DIR
    - echo $CI_PROJECT_ID
    - echo $CI_PROJECT_NAME
    - echo $CI_PROJECT_NAMESPACE
    - echo $CI_PROJECT_PATH
    - echo $CI_PROJECT_TITLE
    - echo $CI_PROJECT_URL
    - echo $CI_PROJECT_VISIBILITY
    - echo $CI_RUNNER_DESCRIPTION
    - echo $CI_RUNNER_ID
    - echo $CI_RUNNER_REVISION
    - echo $CI_SERVER_URL
    - echo $CI_SERVER_NAME
    - echo $CI_SERVER_VERSION
    - echo $GITLAB_CI
    - echo $GITLAB_USER_EMAIL
    - echo $GITLAB_USER_ID
    - echo $GITLAB_USER_LOGIN
    - echo $GITLAB_USER_NAME