image:
  name: golang:1.13.1-stretch
  entrypoint: ["/bin/sh", "-c"]

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is mydomainperso.com, and that your repository is repos/projectname, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/mydomainperso.com/repos/projectname
# Thus, making a symbolic link corrects this.
# 为了能够使用go get，需要将代码放在 $GOPATH 中，
# 比如你的 gitlab 域名是 mydomain.com，你的代码仓库是 repos/projectname，
# 默认的 GOPATH 是 /go，然后你就需要将你的代码放置到 GOPATH 下面，
# /go/src/mydomain.com/repos/projectname，用一个软链接指过来就可以了
before_script:
  - mkdir -p "/go/src/gitlab.ranzhendong.com.cn/${CI_PROJECT_NAMESPACE}"
  - ln -sf "${CI_PROJECT_DIR}" "/go/src/gitlab.ranzhendong.com.cn/${CI_PROJECT_PATH}"
  - cd "/go/src/gitlab.ranzhendong.com.cn/${CI_PROJECT_PATH}/"

stages:
  - test
  - build
  - release
  - review
  - deploy

#test:
#  stage: test
#  script:
#    - make test

test2:
  stage: test
  script:
    - sleep 3
    - echo "We did it! Something else runs in parallel!"
    - echo CI_PROJECT_NAMESPACE
    - echo CI_PROJECT_DIR
    - echo CI_PROJECT_PATH

compile:
  stage: build
  script:
    # Add here all the dependencies, or use glide/govendor/...
    # to get them automatically.
    - make build
  artifacts:
    paths:
      - app

image_build:
  stage: release
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://localhost:2375
    VERSION: 'cat VERSION'
  services:
    - name: docker:17.03-dind
      command: ["--insecure-registry=gitlab.ranzhendong.com.cn"]
  script:
    - docker info
    - docker login -u "${CI_HARBOR_USER}" -p "${CI_HARBOR_PASSWORD}" "${CI_HARBOR_URL}"
    - docker build -t "${CI_REGISTRY_IMAGE}:latest" .
    - docker tag "${CI_REGISTRY_IMAGE}:latest" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}:${VERSION}"
    - test ! -z "${CI_COMMIT_TAG}" && docker push "${CI_REGISTRY_IMAGE}:${VERSION}"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}:${VERSION}"