# IrishMan config

# server config
server:
  bind: 0.0.0.0:8080
  readtimeout: 15
  writetimeout: 15

# etcd config
etcd:
  host: 172.16.0.51:2379
  format: json
  timeout: 2

# resource named
resource:
  upstreamlist: UpstreamList
  uplist: UpList
  downlist: DownList

# upstream config
upstream:
  etcdprefix: Upstream
  reserved:
    - all
    - healthcheck
    - upstream
    - somethingElse

# health check config
healthcheck:
  etcdprefix: HealthCheck
  template:
    status: running
    checkProtocol: http
    checkPath: /
    health:
      interval: 3000
      successTime: 3
      successTimeout: 3000
      successStatus:
        - 200
        - 302
    unhealth:
      interval: 4500
      failuresTime: 3
      FailuresTimeout: 2000
      failuresStatus:
        - 429
        - 404
        - 500
        - 501
        - 502
        - 503
        - 504