# IrishMan config

# server config
server:
  bind: 0.0.0.0:8080
  readtimeout: 15
  writetimeout: 15

# etcd config
etcd:
  host: 172.16.0.51:2379
  format: json
  timeout: 2

# upstream config
upstream:
  etcdprefix: Upstream
  reserved:
    - all
    - healthcheck
    - upstream
    - somethingElse

# health check config
healthcheck:
  etcdprefix: HealthCheck